# Dogs

In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec

Using TensorFlow backend.


## Preparing

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ianmcloughlin/datasets/master/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
..    ...  ...     ...     ...       ...
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

In [3]:
pureenc = pre.LabelBinarizer()
pureenc.fit(df['pure'])
df['pureenc'] = pureenc.transform(df['pure'])

In [4]:
x = df[['pureenc', 'age', 'weight', 'height']]
y = df['lifespan']

In [5]:
x

pureenc  age  weight  height
0         1    3    7.94    49.6
1         1    7    5.05    63.5
2         1    6   16.15    68.2
3         0    3   15.50    64.7
4         0    3   12.17    59.7
..      ...  ...     ...     ...
95        0    4   20.76    52.2
96        0    4   17.40    47.5
97        0    6   15.60    51.4
98        0    3    8.37    54.1
99        1    7    9.09    50.3

[100 rows x 4 columns]

In [6]:
y

0     15
1     17
2     11
3     12
4     14
      ..
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [7]:
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

## Building and training

In [8]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [9]:
m.fit(x_train, y_train, epochs=100, batch_size=10)




Epoch 1/100





70/70 [==============================] - 0s 6ms/step - loss: 175.8444
Epoch 2/100
70/70 [==============================] - 0s 100us/step - loss: 123.7820
Epoch 3/100
70/70 [==============================] - 0s 129us/step - loss: 83.6754
Epoch 4/100
70/70 [==============================] - 0s 171us/step - loss: 53.2582
Epoch 5/100
70/70 [==============================] - 0s 85us/step - loss: 34.8661
Epoch 6/100
70/70 [==============================] - 0s 129us/step - loss: 23.9039
Epoch 7/100
70/70 [==============================] - 0s 100us/step - loss: 18.7403
Epoch 8/100
70/70 [==============================] - 0s 186us/step - loss: 16.5571
Epoch 9/100
70/70 [==============================] - 0s 129us/step - loss: 15.8359
Epoch 10/100
70/70 [==============================] - 0s 157us/step - loss: 15.8823
Epoch 11/100
70/70 [==============================] - 0s 257us/step - loss: 15.7769
Epoch 12/100
70/70 [==============================] - 0s 286us/step - loss: 15

70/70 [==============================] - 0s 557us/step - loss: 7.8257
Epoch 80/100
70/70 [==============================] - 0s 329us/step - loss: 7.8065
Epoch 81/100
70/70 [==============================] - 0s 243us/step - loss: 7.7480
Epoch 82/100
70/70 [==============================] - 0s 416us/step - loss: 7.7404
Epoch 83/100
70/70 [==============================] - 0s 329us/step - loss: 7.7005
Epoch 84/100
70/70 [==============================] - 0s 629us/step - loss: 7.6752
Epoch 85/100
70/70 [==============================] - 0s 629us/step - loss: 7.6577
Epoch 86/100
70/70 [==============================] - 0s 257us/step - loss: 7.6195
Epoch 87/100
70/70 [==============================] - 0s 429us/step - loss: 7.6587
Epoch 88/100
70/70 [==============================] - 0s 786us/step - loss: 7.5659
Epoch 89/100
70/70 [==============================] - 0s 329us/step - loss: 7.5136
Epoch 90/100
70/70 [==============================] - 0s 271us/step - loss: 7.6498
Epoch 91/100
70/7

In [10]:
m.predict(x_test).round().T

array([[ 9., 17., 14., 15., 13., 13.,  9., 16., 16., 15., 14., 16., 14.,
        18., 12.,  6., 16., 14., 12., 14., 12.,  6., 16.,  9., 12., 11.,
        13., 11., 13., 15.]], dtype=float32)

In [11]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 11., 16.,  9., 10., 10., 15., 18., 16., 13., 14., 17., 11.,
       17., 14., 12., 12., 12., 15., 14., 11., 12., 11., 12., 15., 17.,
       12.,  8., 15., 14.], dtype=float32)

In [12]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 10ms/step


12.003971099853516

## Scaling

In [13]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [14]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [15]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 1s 15ms/step - loss: 40.7511
Epoch 2/100
70/70 [==============================] - 0s 500us/step - loss: 23.7492
Epoch 3/100
70/70 [==============================] - 0s 243us/step - loss: 16.7614
Epoch 4/100
70/70 [==============================] - 0s 286us/step - loss: 15.9313
Epoch 5/100
70/70 [==============================] - 0s 172us/step - loss: 16.0746
Epoch 6/100
70/70 [==============================] - 0s 400us/step - loss: 15.6157
Epoch 7/100
70/70 [==============================] - 0s 272us/step - loss: 14.9831
Epoch 8/100
70/70 [==============================] - 0s 229us/step - loss: 14.5043
Epoch 9/100
70/70 [==============================] - 0s 243us/step - loss: 14.2298
Epoch 10/100
70/70 [==============================] - 0s 415us/step - loss: 13.8845
Epoch 11/100
70/70 [==============================] - 0s 400us/step - loss: 13.5412
Epoch 12/100
70/70 [==============================] - 0s 285us/step - loss: 13.1947
Ep

70/70 [==============================] - 0s 186us/step - loss: 6.9660
Epoch 100/100
70/70 [==============================] - 0s 129us/step - loss: 6.9669


In [16]:
m.predict(x_test).round().T

array([[ 9., 17., 15., 15., 13., 13.,  9., 16., 16., 16., 14., 17., 14.,
        19., 13.,  6., 16., 14., 13., 14., 12.,  5., 16.,  9., 12., 11.,
        14., 11., 14., 15.]], dtype=float32)

In [17]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 11., 16.,  9., 10., 10., 15., 18., 16., 13., 14., 17., 11.,
       17., 14., 12., 12., 12., 15., 14., 11., 12., 11., 12., 15., 17.,
       12.,  8., 15., 14.], dtype=float32)

In [18]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 5ms/step


11.587384223937988

## Whitening

In [19]:
pca = dec.PCA(n_components=4, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

pureenc       age    weight    height
0   0.736344 -0.947150 -0.650070 -0.890905
1   0.503805  0.907259  1.235562  1.011582
2   0.974486 -0.962635 -0.142712  1.105679
3   0.669764  0.811331  1.719606 -1.006800
4   0.072978  1.519562 -0.616789 -1.024494
..       ...       ...       ...       ...
65 -0.935858 -1.577010 -0.961254 -0.685203
66 -2.332158 -0.032905 -0.728702 -0.674602
67 -0.532962 -0.339450  0.838967  1.205777
68 -0.637194  1.386388 -0.227541 -0.943898
69  1.454682 -0.213017  0.081934  1.002329

[70 rows x 4 columns]

In [20]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=4, activation="tanh"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [21]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 1s 17ms/step - loss: 158.6180
Epoch 2/100
70/70 [==============================] - 0s 428us/step - loss: 134.5251
Epoch 3/100
70/70 [==============================] - 0s 457us/step - loss: 111.7644
Epoch 4/100
70/70 [==============================] - 0s 415us/step - loss: 90.5519
Epoch 5/100
70/70 [==============================] - 0s 271us/step - loss: 71.9324
Epoch 6/100
70/70 [==============================] - 0s 286us/step - loss: 56.6963
Epoch 7/100
70/70 [==============================] - 0s 243us/step - loss: 44.0425
Epoch 8/100
70/70 [==============================] - 0s 422us/step - loss: 34.4441
Epoch 9/100
70/70 [==============================] - 0s 279us/step - loss: 27.1206
Epoch 10/100
70/70 [==============================] - 0s 271us/step - loss: 21.2781
Epoch 11/100
70/70 [==============================] - 0s 243us/step - loss: 16.4516
Epoch 12/100
70/70 [==============================] - 0s 228us/step - loss: 12.8540

70/70 [==============================] - 0s 300us/step - loss: 1.4436
Epoch 100/100
70/70 [==============================] - 0s 1ms/step - loss: 1.4074


In [22]:
m.predict(x_test).round().T

array([[10., 13., 15., 11., 11., 11., 13., 16., 15., 13., 14., 16., 12.,
        16., 14., 10., 14., 12., 14., 14., 11., 10., 13., 11., 14., 15.,
        12., 10., 14., 15.]], dtype=float32)

In [23]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 11., 16.,  9., 10., 10., 15., 18., 16., 13., 14., 17., 11.,
       17., 14., 12., 12., 12., 15., 14., 11., 12., 11., 12., 15., 17.,
       12.,  8., 15., 14.], dtype=float32)

In [24]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 10ms/step


1.8622918128967285

## End