# Classification of Iris

## Package imports

In [15]:
# For building neural networks.
from tensorflow import keras
import tensorflow.keras as kr

# For interacting with data sets.
import pandas as pd

# For encoding categorical variables.
import sklearn.preprocessing as pre

# For splitting into training and test sets.
import sklearn.model_selection as mod

#--------------My own imports------------------------
from tensorflow.python.keras import backend as k
from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
##from tensorflow. keras.utils import plot_model

import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
print(tf.keras.__version__) # Keras version 2.2.4
print(tf.__version__) # Tensorflow version 2.0.0

# ISSUE OF DEFAULT MODELS NOT FOUND ETC SOLVED BY: tensorflow.keras INSTEAD of just keras see:
# https://stackoverflow.com/questions/40782271/attributeerror-module-tensorflow-has-no-attribute-reset-default-graph

2.2.4-tf
2.0.0


## Load data

In [2]:
# Load the iris data set from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [6]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Inputs

In [7]:
# Separate the inputs from the rest of the variables.
inputs = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]

In [8]:
inputs

petal_length  petal_width  sepal_length  sepal_width
0             1.4          0.2           5.1          3.5
1             1.4          0.2           4.9          3.0
2             1.3          0.2           4.7          3.2
3             1.5          0.2           4.6          3.1
4             1.4          0.2           5.0          3.6
..            ...          ...           ...          ...
145           5.2          2.3           6.7          3.0
146           5.0          1.9           6.3          2.5
147           5.2          2.0           6.5          3.0
148           5.4          2.3           6.2          3.4
149           5.1          1.8           5.9          3.0

[150 rows x 4 columns]

## Encoded outputs

$$
\begin{align*}
  setosa     & \rightarrow  [1,0,0] \\
  versicolor & \rightarrow  [0,1,0] \\
  virginica  & \rightarrow  [0,0,1]
\end{align*}
$$

In [9]:
# Encode the classes as above.
encoder = pre.LabelBinarizer()
encoder.fit(df['species'])
outputs = encoder.transform(df['species'])

outputs

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

## Idea

The neural network will turn four floating point inputs into three "floating point" outputs.

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [0.8, 0.19, 0.01] $$

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [1, 0, 0] $$

## Build model

In [16]:
# from tensorflow.python.keras import backend as kr

# Start a neural network, building it by layers.
model = kr.models.Sequential()

# Add a hidden layer with 64 neurons and an input layer with 4.
model.add(kr.layers.Dense(units=64, activation='relu', input_dim=4))
# Add a three neuron output layer.
model.add(kr.layers.Dense(units=3, activation='softmax'))

# Build the graph.
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

## Split

In [17]:
# Split the inputs and outputs into training and test sets.
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.5)

In [18]:
inputs_test.iloc[0]

petal_length    1.1
petal_width     0.1
sepal_length    4.3
sepal_width     3.0
Name: 13, dtype: float64

In [19]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\Gareth Duffy\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.54350233, 0.22363795, 0.23285963]], dtype=float32)

## Train

In [20]:
# Train the neural network.
model.fit(inputs_train, outputs_train, epochs=15, batch_size=10)

Train on 75 samples
Epoch 1/15
75/75 [==============================] - 2s 23ms/sample - loss: 0.9672 - accuracy: 0.5600
Epoch 2/15
75/75 [==============================] - 0s 493us/sample - loss: 0.8288 - accuracy: 0.7200
Epoch 3/15
75/75 [==============================] - 0s 373us/sample - loss: 0.7878 - accuracy: 0.6533
Epoch 4/15
75/75 [==============================] - 0s 386us/sample - loss: 0.7225 - accuracy: 0.6933
Epoch 5/15
75/75 [==============================] - 0s 493us/sample - loss: 0.7009 - accuracy: 0.7600
Epoch 6/15
75/75 [==============================] - 0s 413us/sample - loss: 0.6599 - accuracy: 0.6933
Epoch 7/15
75/75 [==============================] - 0s 346us/sample - loss: 0.6225 - accuracy: 0.7867
Epoch 8/15
75/75 [==============================] - 0s 373us/sample - loss: 0.6155 - accuracy: 0.8000
Epoch 9/15
75/75 [==============================] - 0s 533us/sample - loss: 0.5789 - accuracy: 0.8133
Epoch 10/15
75/75 [==============================] - 0s 347us/s

## Predict

In [21]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\Gareth Duffy\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.83278805, 0.11270473, 0.0545072 ]], dtype=float32)

In [22]:
# Have the network predict the classes of the test inputs.
predictions = model.predict(inputs_test)
predictions_labels = encoder.inverse_transform(predictions)
predictions_labels

array(['setosa', 'virginica', 'setosa', 'virginica', 'virginica',
       'versicolor', 'virginica', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'virginica', 'virginica', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'virginica', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginic

## Evaluate

In [23]:
# Compare the predictions to the actual classes.
predictions_labels == encoder.inverse_transform(outputs_test)

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True, False, False, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True])

In [24]:
(predictions_labels == encoder.inverse_transform(outputs_test)).sum()

55

## End